### ISSUE TITLE
Suggestion: avoid use of elems as a method to return the list of results

### ISSUE THREAD

**Issue by hoelzro** [supernovus/perl6-xml-query#10]
I noticed that `XML::Query::Statement` has an `elems` method to return its list of results.  Since `elems` already has a meaning by convention in the Perl 6 standard library, I think that it could be confusing for people trying to use this library.  I believe that `.list` may be a preferable alternative.

**Comment by supernovus** [comment]
.list does not describe what it is returning though. 'elems' was intentionally chosen back when the library was first created to represent a full set of elements, which corresponds to 'elem' which is a single element. For compatibility, I would keep those two methods in the next few versions (perhaps with warnings that they are deprecated), but I think the more verbose 'element' and 'elements' may be more suitable replacements going forward. I will make this change in the next release.

**Comment by supernovus** [comment]
The newest release has renamed 'elem' to 'element' and 'elems' to 'elements'. The previous method names are currently available and will spit out a warning if used. In the next release they should be removed entirely.

**Comment by hoelzro** [comment]
@supernovus Works for me, thanks!
