### ISSUE TITLE
Works until compiled because of custom .new

### ISSUE THREAD

**Issue by zostay** [supernovus/perl6-xml-query#3]
This is probably an R* or a MoarVM bug, but the tests pass when running against the source, but fail as soon as there's a compiled mbc file available:

    [9:04] sterling@Weasley perl6-xml-query#master% prove -e 'perl6' t
    t/basic.t .. Default constructor for 'Query' only takes named arguments
      in method new at src/gen/m-CORE.setting:970
      in block <unit> at t/basic.t:14

    t/basic.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 28/28 subtests

    Test Summary Report
    -------------------
    t/basic.t (Wstat: 65280 Tests: 0 Failed: 0)
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 28 tests but ran 0.
    Files=1, Tests=0,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.54 cusr  0.05 csys =  0.62 CPU)
    Result: FAIL
    [9:04] sterling@Weasley perl6-xml-query#master% prove -e 'perl6 -Ilib' t
    t/basic.t .. ok
    All tests successful.
    Files=1, Tests=28,  1 wallclock secs ( 0.02 usr  0.01 sys +  1.20 cusr  0.07 csys =  1.30 CPU)
    Result: PASS

So, here you can see it passes if I make it use the local lib, but if it uses the lib from the already installed copy of the same module.

Is there a work around in the meantime aside from manually installing without letting Panda compile the mbc target?

**Comment by supernovus** [comment]
I know it's a year later, and I'm sorry I never noticed this bug report until now, but this does not appear to happen anymore, so I'm closing this issue.
